# Generated by Django 5.0 on 2024-05-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
