# Generated by Django 5.0 on 2024-05-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_country_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
